In [1]:
import  tensorflow as tf #1 import 

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data() #2 test,train
x_train,x_test=x_train/255.0,x_test/255.0

In [3]:
x_train[0].shape

(28, 28)

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10,activation='softmax')
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),metrics=['sparse_categorical_accuracy'])

In [7]:
model.fit(x_train, y_train,batch_size=32,epochs=10,validation_data=(x_test, y_test),validation_freq=2)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 4s 62us/sample - loss: 0.2610 - sparse_categorical_accuracy: 0.9258
Epoch 2/10
60000/60000 [==============================] - 4s 60us/sample - loss: 0.1153 - sparse_categorical_accuracy: 0.9656 - val_loss: 0.0941 - val_sparse_categorical_accuracy: 0.9707
Epoch 3/10
60000/60000 [==============================] - 3s 54us/sample - loss: 0.0791 - sparse_categorical_accuracy: 0.9762
Epoch 4/10
60000/60000 [==============================] - 4s 59us/sample - loss: 0.0586 - sparse_categorical_accuracy: 0.9822 - val_loss: 0.0784 - val_sparse_categorical_accuracy: 0.9765
Epoch 5/10
60000/60000 [==============================] - 3s 56us/sample - loss: 0.0462 - sparse_categorical_accuracy: 0.9858
Epoch 6/10
60000/60000 [==============================] - 4s 60us/sample - loss: 0.0368 - sparse_categor

In [8]:
import numpy as np

In [9]:
x = np.zeros((2,2,3))
x

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
x[0,0,1]=3
x[0,1,0]=2
x[0,1,2]=1
x[1,0,0]=3
x[1,0,2]=1

In [11]:
x

array([[[0., 3., 0.],
        [2., 0., 1.]],

       [[3., 0., 1.],
        [0., 0., 0.]]])

In [12]:
tf.keras.utils.to_categorical(x)

array([[[[1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [1., 0., 0., 0.]],

        [[0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.]]],


       [[[0., 0., 0., 1.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.]],

        [[1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.]]]], dtype=float32)

In [13]:
b = [1,2,3,4,5]
tf.keras.utils.to_categorical(b)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [14]:
def convert_to_one_hot(labels, num_classes):
    #计算向量有多少行
    num_labels = len(labels)
    #生成值全为0的独热编码的矩阵
    labels_one_hot = np.zeros((num_labels, num_classes))
    #计算向量中每个类别值在最终生成的矩阵“压扁”后的向量里的位置
    index_offset = np.arange(num_labels) * num_classes
    #遍历矩阵，为每个类别的位置填充1
    labels_one_hot.flat[index_offset + labels] = 1
    return labels_one_hot
#进行测试
b = [2, 4, 6, 8, 6, 2, 3, 7]
print(convert_to_one_hot(b,9))

[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [18]:
!free -h

              total        used        free      shared  buff/cache   available
Mem:           1.8G        161M        1.4G         24K        259M        1.5G
Swap:          2.0G        1.6G        406M
