In [13]:
import tensorflow as tf

In [14]:
print('Tensorflow version: {}'.format(tf.__version__))

Tensorflow version: 2.0.0-beta1


In [15]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [16]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [17]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [7]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [8]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [10]:
for ele in dataset.take(2):
    print(ele)
    print(ele.numpy())# tensor -> numpy数据类型

tf.Tensor([1 2], shape=(2,), dtype=int32)
[1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32)
[3 4]


In [9]:
dataset_dic = tf.data.Dataset.from_tensor_slices({'a': [1,2,3,4],
                                                  'b': [6,7,8,9],
                                                  'c': [12,13,14,15]
    
})

In [10]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [14]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: id=60, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=61, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=62, shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: id=66, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=67, shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: id=68, shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: id=72, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=73, shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: id=74, shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: id=78, shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: id=79, shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: id=80, shape=(), dtype=int32, numpy=15>}


In [21]:
import numpy as np

In [23]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))
dataset.take(4)

<TakeDataset shapes: (), types: tf.int64>

In [24]:
for ele in dataset.take(4):
    print(ele.numpy())

1
2
3
4


In [22]:
next(iter(dataset.take(1)))

<tf.Tensor: id=146, shape=(), dtype=int32, numpy=1>

In [33]:
np.linspace(0,9,num=10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [60]:
dataset = tf.data.Dataset.from_tensor_slices(np.linspace(0,9,num=10))
dataset = dataset.shuffle(100)
# dataset = dataset.repeat()
# dataset = dataset.batch(3)

In [76]:
dataset = tf.data.Dataset.from_tensor_slices(np.linspace(0,9,num=10))

In [49]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [77]:
for ele in dataset.batch(2):
    print(ele.numpy())

[0. 1.]
[2. 3.]
[4. 5.]
[6. 7.]
[8. 9.]


In [50]:
dataset = dataset.map(tf.square)

In [35]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
49


In [12]:
(train_image, train_label), (test_image, test_label) = tf.keras.datasets.fashion_mnist.load_data()