In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0-beta1'

In [3]:
a = tf.constant(2.)
b = tf.constant(4.)

In [4]:
print('a + b = ',a+b)

a + b =  tf.Tensor(6.0, shape=(), dtype=float32)


In [5]:
type(a)

tensorflow.python.framework.ops.EagerTensor

## 动态图优先模式
这种运算时同时创建计算图𝑎 + 𝑏和计算数值结果2.0 + 4.0的方式叫做命令式编程，也称为动态图优先模式

In [7]:
tf.device('/cpu:0')

In [8]:
tf.device('/gpu:0')

In [10]:
with tf.device('/cpu:0'):
    n = 10
    cpu_a = tf.random.normal([1, n])
    cpu_b = tf.random.normal([n, 1])
    print(cpu_a.device, cpu_b.device)

/job:localhost/replica:0/task:0/device:CPU:0 /job:localhost/replica:0/task:0/device:CPU:0


In [11]:
y = tf.constant([0,1,2,3])

In [12]:
y

<tf.Tensor: id=16, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [14]:
y = tf.one_hot(y,depth=4)

In [20]:

for i in y:
    print(i.numpy(),i.numpy().shape)

[1. 0. 0. 0.] (4,)
[0. 1. 0. 0.] (4,)
[0. 0. 1. 0.] (4,)
[0. 0. 0. 1.] (4,)


In [22]:
i.numpy()[0]

0.0

In [23]:
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers, datasets


In [27]:
# 加载 MNIST 数据集
(x, y), (x_val, y_val) = datasets.mnist.load_data()
# 转换为浮点张量， 并缩放到-1~1
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
# 转换为整形张量
y = tf.convert_to_tensor(y, dtype=tf.int32)
# one-hot 编码
y = tf.one_hot(y, depth=10)
print(x.shape, y.shape)
# 构建数据集对象
train_dataset = tf.data.Dataset.from_tensor_slices((x, y))
print('batch old',train_dataset)
# 批量训练
train_dataset = train_dataset.batch(200)

(60000, 28, 28) (60000, 10)
batch old <TensorSliceDataset shapes: ((28, 28), (10,)), types: (tf.float32, tf.float32)>


In [38]:
for i,j in train_dataset.take(1):
    print(i.numpy())
    print(i)
    print(j)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
tf.Tensor(

In [39]:
model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10,activation='softmax')])

In [80]:
model.compile(optimizer='SGD',loss=keras.losses.CategoricalCrossentropy(),metrics=['categorical_accuracy'])

In [81]:
model.fit(train_dataset,)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


InvalidArgumentError:  Incompatible shapes: [200,10] vs. [200,28,10]
	 [[node SGD/gradients_1/loss_1/output_1_loss/mul_grad/BroadcastGradientArgs (defined at <ipython-input-81-50bee5f74f82>:1) ]] [Op:__inference_keras_scratch_graph_2676]

Function call stack:
keras_scratch_graph


In [43]:
x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  y = x * x
dy_dx = g.gradient(y, x) # Will compute to 6.0

In [45]:
tf.constant("hello world")

<tf.Tensor: id=1895, shape=(), dtype=string, numpy=b'hello world'>

In [46]:
tf.constant(1,dtype=float)

<tf.Tensor: id=1897, shape=(), dtype=float32, numpy=1.0>

In [54]:
tf.constant([1]).shape

TensorShape([1])

In [49]:
tf.constant([1,2,3,4,5]).numpy()

array([1, 2, 3, 4, 5], dtype=int32)

In [53]:
tf.constant(1).shape

TensorShape([])

In [51]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: id=1907, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [52]:
tf.constant([[1,2],[3,4]]).shape

TensorShape([2, 2])

In [55]:
import numpy as np

In [56]:
tf.constant(np.pi,dtype=tf.float32)

<tf.Tensor: id=1912, shape=(), dtype=float32, numpy=3.1415927>

In [57]:
tf.constant(np.pi,dtype=tf.float16)

<tf.Tensor: id=1914, shape=(), dtype=float16, numpy=3.14>

In [59]:
a = tf.Variable(1)

In [60]:
a.name

'Variable:0'

In [61]:
a.trainable

True

In [62]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=1932, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [63]:
y = tf.constant([1.01,2.01,-0.66])
y_pro = tf.nn.softmax(y)
y_pro

<tf.Tensor: id=1935, shape=(3,), dtype=float32, numpy=array([0.25598174, 0.69583046, 0.04818781], dtype=float32)>

In [70]:
sum = 0.0
for i in y:
    sum += np.exp(i.numpy())
for i in y:
    print(np.exp(i.numpy())/sum)

0.2559817179747941
0.6958304760815138
0.048187805943692104


In [69]:
for i in y:
    print(np.exp(i.numpy())/sum)

0.2559817179747941
0.6958304760815138
0.048187805943692104


In [73]:
tf.Variable([1,2,3]).assign_sub([2,2,2])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([-1,  0,  1], dtype=int32)>

### 二分类: 已知答案y_=(1,0) 预测y1=(0.6,0.4) y2 =(0.8,0.2) 那个最接近正确答案

H(y_,y) = - sum(y_*lny)

In [79]:
h1 = tf.losses.categorical_crossentropy([1,0],[0.6,0.4])
h2 = tf.losses.categorical_crossentropy([1,0],[0.8,0.2])
h1,h2

(<tf.Tensor: id=2088, shape=(), dtype=float32, numpy=0.5108256>,
 <tf.Tensor: id=2106, shape=(), dtype=float32, numpy=0.22314353>)