In [1]:
import numpy as np

In [7]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.expand_dims(a,axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [9]:
np.expand_dims(a,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [11]:
b = a.reshape(3,-1)

In [14]:
c = np.expand_dims(b,axis=-1)
print(a.shape,b.shape,c.shape)

(9,) (3, 3) (3, 3, 1)


In [15]:
np.expand_dims(a,axis=0).shape


(1, 9)

In [16]:
np.expand_dims(a,axis=1).shape

(9, 1)

In [18]:
a[8],a[-1]

(8, 8)

In [19]:
import tensorflow as tf

In [20]:
print(tf.__version__)

2.0.0-beta1


In [21]:
tf.test.is_gpu_available()

False

In [22]:
model = tf.keras.models.Sequential()

In [24]:
model.add(tf.keras.layers.Conv2D(32,(3,3),input_shape=(28,28,1)))

In [25]:
model.output_shape

(None, 26, 26, 32)

In [27]:
model2 = tf.keras.models.Sequential()

In [43]:
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Conv2D(32,(3,3),input_shape=(28,28,1),padding='same'))
model2.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))
model2.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 14, 14, 32)        0         
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [45]:
model2.add(tf.keras.layers.GlobalAveragePooling2D())

ValueError: Input 0 of layer global_average_pooling2d_1 is incompatible with the layer: expected ndim=4, found ndim=2. Full shape received: [None, 32]

In [47]:
model2.add(tf.keras.layers.Dense(10,activation=tf.ac))
model2.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
global_average_pooling2d (Gl (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 10)                330       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
Total params: 760
Trainable params: 760
Non-trainable params: 0
_________________________________________________________________


In [31]:
model2.output_shape

(None, 28, 28, 32)

In [33]:
model2.summary() # 9*32+32

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 28, 28, 32)        320       
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [36]:
model3 = tf.keras.models.Sequential()
model3.add(tf.keras.layers.Conv2D(32,(3,3),input_shape=(28,28,1),padding='same',use_bias=False))
model3.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 32)        288       
Total params: 288
Trainable params: 288
Non-trainable params: 0
_________________________________________________________________


In [37]:
32*9

288

In [38]:
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 28, 28, 32)        320       
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [40]:
model2.add(tf.keras.layers.MaxPool2D())
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 32)          0         
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [49]:
model.save('test.hdf5')